name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Replace with your default branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Cache Node.js dependencies for faster builds
      - name: Cache Node.js Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 3: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Use the Node.js version compatible with your project
          cache: 'npm' # Adds built-in caching for Node modules

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: npm ci # Faster and ensures a clean slate

      # Step 5: Build the React app
      - name: Build React App
        run: npm run build

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          enable_jekyll: false # Disable Jekyll to prevent conflicts with React routes
